language: python
python:
  - "2.7"
  - "3.2"
  - “3.3”
os:
  #- linux #linux test was failing
  - osx
#travis does not test on windows :(
# command to install dependencies
install: 
  - pip install astroquery
  - pip install astropy
  - pip install scipy
  - pip install base64
  - pip install copy
  - pip install re
   
# command to run tests
script: python tests/test_splat.py

#only test master branch
branches:
  only:
  - master

#notifications:
#  email: false