language: python
python:
  - "2.7"
  - "3.2"
  - “3.3”
os:
  - linux
  - osx
#travis does not test on windows :(
# command to install dependencies
install: 
  - pip install astroquery
  - pip install astropy
  - pip install spicy
  - pip install base64
  - pip install copy
  - pip install re
   
# command to run tests
script: python tests/test_splat.py

#notifications:
#  email: false